from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM
import torch
import random
import os
import sys
import time
import tweepy
from notification_handler import request_confirmation
from dotenv import load_dotenv

load_dotenv()

LLAMA3_MODEL_NAME = "meta-llama/Meta-Llama-3-8B-Instruct"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
TWEET_TIMEGAP_SECS = 60 * 60 * 11 # 11 hours
tokenizer = None
generator = None
CONSUMER_KEY = os.getenv("X_CONSUMER_KEY")
CONSUMER_SECRET = os.getenv("X_CONSUMER_SECRET")
ACCESS_TOKEN = os.getenv("X_ACCESS_TOKEN")
ACCESS_TOKEN_SECRET = os.getenv("X_ACCESS_TOKEN_SECRET")
BEARER_TOKEN = os.getenv("X_BEARER_TOKEN")

def load_llama3_model():
    """
    Loads the Llama 3 model and tokenizer into global variables.
    Requires Hugging Face token login (huggingface-cli login) or HF_TOKEN env var.
    """
    global tokenizer, generator

    print(f"Device set to use {DEVICE}", flush=True)
    print(f"Loading {LLAMA3_MODEL_NAME} model...", flush=True)

    try:
        if os.getenv("HF_TOKEN") is None and not os.path.exists(os.path.expanduser("~/.cache/huggingface/token")):
            print("Warning: Hugging Face token not found. Please run 'huggingface-cli login' or set HF_TOKEN environment variable.", flush=True)
            print(f"Attempting to load model, but might fail with 403 error without token/license acceptance for {LLAMA3_MODEL_NAME}.", flush=True)

        print("Loading tokenizer...", flush=True)
        tokenizer = AutoTokenizer.from_pretrained(LLAMA3_MODEL_NAME)
        print("Tokenizer loaded.", flush=True)

        print("Loading model...", flush=True)
        model = AutoModelForCausalLM.from_pretrained(
            LLAMA3_MODEL_NAME,
            torch_dtype=torch.bfloat16 if DEVICE == "cuda" else torch.float32,
            device_map="auto" if DEVICE == "cuda" else None
        )
        print("Model loaded. Moving to device...", flush=True)
        model.to(DEVICE) 
        print(f"Model moved to {DEVICE}.", flush=True)

        print("Creating text generation pipeline...", flush=True)
        generator = pipeline(
            'text-generation',
            model=model,
            tokenizer=tokenizer,
            device=0 if DEVICE == "cuda" else -1, 
            max_new_tokens=200, 
            do_sample=True,
            temperature=0.7,
            top_k=50,
            top_p=0.95,
            repetition_penalty=1.1,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.eos_token_id,
        )
        print("Text generation pipeline created.", flush=True)
        print("Model and pipeline loaded successfully!", flush=True)
    except Exception as e:
        print(f"Error loading model: {e}", flush=True)
        print("Please ensure you have accepted the Llama 3 license on Hugging Face and logged in via 'huggingface-cli login' or set HF_TOKEN.", flush=True)
        sys.exit(1) 

def generate_technical_tweet(topic: str) -> str:
    """
    Generates a technical tweet about a given topic using the loaded Llama 3 model.

    Args:
        topic (str): The technical topic for the tweet.

    Returns:
        str: The cleaned and truncated tweet text.
    """
    if generator is None or tokenizer is None:
        raise RuntimeError("Model and tokenizer not loaded. Call load_llama3_model() first.")

    messages = [
        {"role": "system", "content": "You are a concise, expert technical writer for Twitter. Your goal is to provide clear, actionable technical details, insights or tips. Keep tweets under 280 characters. Avoid repeating previous suggestions."},
        {"role": "user", "content": f"Suggest a crucial technical detail about {topic} for developers to know. Dont add 'Did you know' in the output. Ensure the output is unique and not similar to any previously provided examples."},
    ]

    print(f"\n--- Generating for topic: {topic} ---", flush=True)
    print(f"--- Applying chat template... ---", flush=True)
    prompt_llama3 = tokenizer.apply_chat_template( # This was missing a print before it
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    print(f"--- Generated Prompt for Llama 3 ---\n{prompt_llama3}", flush=True)

    generated_output = generator(prompt_llama3)
    raw_generated_text = generated_output[0]['generated_text']

    print(f"Generated (raw): {raw_generated_text}\n")

    clean_tweet_text = post_process_llama3_output(raw_generated_text)

    if len(clean_tweet_text) > 280:
        clean_tweet_text = clean_tweet_text[:277] + "..."

    return clean_tweet_text

def post_process_llama3_output(raw_text: str) -> str:
    """
    Extracts and cleans the assistant's response from Llama 3 raw output.

    Args:
        raw_text (str): The raw text generated by the Llama 3 model.

    Returns:
        str: The cleaned response.
    """
    try:
        assistant_start_index = raw_text.rfind("<|start_header_id|>assistant<|end_header_id|>\n\n")
        if assistant_start_index != -1:
            clean_text = raw_text[assistant_start_index + len("<|start_header_id|>assistant<|end_header_id|>\n\n"):].strip()
            clean_text = clean_text.replace("<|eot_id|>", "").strip()
            return clean_text
        else:
            return raw_text.replace("<|eot_id|>", "").strip() # Still remove eot_id if present
    except Exception as e:
        print(f"Error during post-processing: {e}. Returning raw text as fallback.", flush=True)
        return raw_text.replace("<|eot_id|>", "").strip()

def main():
    """
    Main function to run the tweet generation process.
    """
    if not all([CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET]):
        print("Error: X API credentials not set. Please set X_CONSUMER_KEY, X_CONSUMER_SECRET, X_ACCESS_TOKEN, X_ACCESS_TOKEN_SECRET environment variables.", flush=True)
        raise ValueError("Please set your X API credentials as environment variables.")

    force_post = len(sys.argv) > 1 and sys.argv[1] == "--force-post"

    print("Starting main function. Calling load_llama3_model...", flush=True)
    load_llama3_model()

    x_client = tweepy.Client(
        bearer_token=BEARER_TOKEN,  
        consumer_key=CONSUMER_KEY,
        consumer_secret=CONSUMER_SECRET,
        access_token=ACCESS_TOKEN,
        access_token_secret=ACCESS_TOKEN_SECRET
    )

    topics = [
        "kubernetes", "docker", "c++", "golang", "java", "nodejs", "redis",
        "python", "system design", "data structures and algorithms",
        "operating system", "computer networking", "databases", "kafka", "javascript"
    ]

    print(f"Initialization complete. Starting tweet generation loop every {TWEET_TIMEGAP_SECS} seconds.", flush=True)

    try:
        while True:
            print("--- New tweet cycle started ---", flush=True)
            selected_topic = random.choice(topics)
            tweet = generate_technical_tweet(selected_topic)
            print(f"\n--- Proposed Tweet for Twitter ---\n'{tweet}'", flush=True)
            
            if force_post:
                print("Command line argument '--force-post' detected. Skipping confirmation and posting directly.", flush=True)
                confirmed_to_post_decision = "approve"
            else:
                while True:
                    try:
                        confirmed_to_post_decision = request_confirmation(tweet, timeout=TWEET_TIMEGAP_SECS)
                        break
                    except TimeoutError:
                        print(f"Timeout of {TWEET_TIMEGAP_SECS}s reached without response. Retrying confirmation request...", flush=True)
                print(f"Confirmation decision: {confirmed_to_post_decision}", flush=True)

            if confirmed_to_post_decision == "approve":
                print("Posting tweet...", flush=True)
                response = x_client.create_tweet(text=tweet)
                print("Tweet posted successfully!", flush=True)
                print(f"Tweet ID: {response.data['id']}", flush=True)
                print(f"Tweet Text: {response.data['text']}", flush=True)
            elif confirmed_to_post_decision == "reject":
                print("Tweet posting rejected by user.", flush=True)
            elif confirmed_to_post_decision == "regenerate":
                print("Re-generating new tweet as requested by the user.", flush=True)
                continue

            print(f"Waiting for {TWEET_TIMEGAP_SECS} seconds before next cycle...", flush=True)
            time.sleep(TWEET_TIMEGAP_SECS)
    except KeyboardInterrupt:
        print("\nTask stopped by user.", flush=True)
    except Exception as e:
        print(f"An unexpected error occurred in main loop: {e}", flush=True)

if __name__ == "__main__":
    main()