from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM
import torch
import random
import os
import sys 
import time
import requests
import json
import uuid
import tweepy

LLAMA3_MODEL_NAME = "meta-llama/Meta-Llama-3-8B-Instruct"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
TWEET_TIMEGAP_SECS = 60 * 60 * 12 # 12 hours
tokenizer = None
generator = None
CONSUMER_KEY = os.environ.get("X_CONSUMER_KEY")
CONSUMER_SECRET = os.environ.get("X_CONSUMER_SECRET")
ACCESS_TOKEN = os.environ.get("X_ACCESS_TOKEN")
ACCESS_TOKEN_SECRET = os.environ.get("X_ACCESS_TOKEN_SECRET")
BEARER_TOKEN = os.environ.get("X_BEARER_TOKEN")

NTFY_SERVER = "https://ntfy.sh"
NTFY_CONFIRM_TOPIC = os.environ.get("NTFY_CONFIRM_TOPIC")
NTFY_RESPONSE_TOPIC = os.environ.get("NTFY_RESPONSE_TOPIC")
TWEET_CONFIRMATION_TIMEOUT_SECS = int(os.environ.get("TWEET_CONFIRMATION_TIMEOUT_SECS", 3000)) # 50 minutes default


def load_llama3_model():
    """
    Loads the Llama 3 model and tokenizer into global variables.
    Requires Hugging Face token login (huggingface-cli login) or HF_TOKEN env var.
    """
    global tokenizer, generator

    print(f"Device set to use {DEVICE}")
    print(f"Loading {LLAMA3_MODEL_NAME} model...")

    try:
        if os.getenv("HF_TOKEN") is None and not os.path.exists(os.path.expanduser("~/.cache/huggingface/token")):
            print("Warning: Hugging Face token not found. Please run 'huggingface-cli login' or set HF_TOKEN environment variable.")
            print(f"Attempting to load model, but might fail with 403 error without token/license acceptance for {LLAMA3_MODEL_NAME}.")

        tokenizer = AutoTokenizer.from_pretrained(LLAMA3_MODEL_NAME)
        model = AutoModelForCausalLM.from_pretrained(
            LLAMA3_MODEL_NAME,
            torch_dtype=torch.bfloat16 if DEVICE == "cuda" else torch.float32,
            device_map="auto" if DEVICE == "cuda" else None
        )
        model.to(DEVICE) 

        generator = pipeline(
            'text-generation',
            model=model,
            tokenizer=tokenizer,
            device=0 if DEVICE == "cuda" else -1, 
            max_new_tokens=200, 
            do_sample=True,
            temperature=0.7,
            top_k=50,
            top_p=0.95,
            repetition_penalty=1.1,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.eos_token_id,
        )
        print("Model loaded successfully!")
    except Exception as e:
        print(f"Error loading model: {e}")
        print("Please ensure you have accepted the Llama 3 license on Hugging Face and logged in via 'huggingface-cli login' or set HF_TOKEN.")
        sys.exit(1) 

def generate_technical_tweet(topic: str) -> str:
    """
    Generates a technical tweet about a given topic using the loaded Llama 3 model.

    Args:
        topic (str): The technical topic for the tweet.

    Returns:
        str: The cleaned and truncated tweet text.
    """
    if generator is None or tokenizer is None:
        raise RuntimeError("Model and tokenizer not loaded. Call load_llama3_model() first.")

    messages = [
        {"role": "system", "content": "You are a concise, expert technical writer for Twitter. Your goal is to provide clear, actionable technical insights and tips. Keep tweets under 280 characters."},
        {"role": "user", "content": f"Suggest a crucial technical detail about {topic} for developers to know. Dont add 'Did you know' in the output"},
    ]

    prompt_llama3 = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    print(f"\n--- Generating for topic: {topic} ---")
    print(f"--- Generated Prompt for Llama 3 ---\n{prompt_llama3}")

    generated_output = generator(prompt_llama3)
    raw_generated_text = generated_output[0]['generated_text']

    print(f"Generated (raw): {raw_generated_text}\n")

    clean_tweet_text = post_process_llama3_output(raw_generated_text)

    if len(clean_tweet_text) > 280:
        clean_tweet_text = clean_tweet_text[:277] + "..."

    return clean_tweet_text

def post_process_llama3_output(raw_text: str) -> str:
    """
    Extracts and cleans the assistant's response from Llama 3 raw output.

    Args:
        raw_text (str): The raw text generated by the Llama 3 model.

    Returns:
        str: The cleaned response.
    """
    try:
        assistant_start_index = raw_text.rfind("<|start_header_id|>assistant<|end_header_id|>\n\n")
        if assistant_start_index != -1:
            clean_text = raw_text[assistant_start_index + len("<|start_header_id|>assistant<|end_header_id|>\n\n"):].strip()
            clean_text = clean_text.replace("<|eot_id|>", "").strip()
            return clean_text
        else:
            return raw_text.replace("<|eot_id|>", "").strip() # Still remove eot_id if present
    except Exception as e:
        print(f"Error during post-processing: {e}. Returning raw text as fallback.")
        return raw_text.replace("<|eot_id|>", "").strip()

def request_phone_confirmation_ntfy(tweet_text: str, confirmation_timeout_seconds: int) -> bool:
    """
    Requests confirmation via ntfy push notification to a phone.
    Returns True if approved, False otherwise (rejected or timed out).
    """
    if not all([NTFY_SERVER, NTFY_CONFIRM_TOPIC, NTFY_RESPONSE_TOPIC]):
        print("Ntfy server/topic environment variables not set. Falling back to terminal confirmation.")
        user_input = input(f"Post tweet '{tweet_text[:70].replace('\n', ' ')}...'? (yes/no): ").strip().lower()
        return user_input in ['yes', 'y']

    confirmation_id = str(uuid.uuid4())
    base_ntfy_url = NTFY_SERVER.rstrip('/')

    message_payload = {
        "topic": NTFY_CONFIRM_TOPIC,
        "message": f"Approve tweet?\n\n---\n{tweet_text}\n---",
        "title": "AutoTweet: Confirm Tweet",
        "priority": 4, # Urgent
        "tags": ["bell", "incoming_call"], # Suggests sound/vibration
        "actions": [
            {
                "action": "http", "label": "Approve ✅",
                "url": f"{base_ntfy_url}/{NTFY_RESPONSE_TOPIC}", "method": "POST",
                "body": json.dumps({"id": confirmation_id, "decision": "approve"}),
                "headers": {"Content-Type": "application/json", "X-Title": f"Approved tweet {confirmation_id[:8]}"}, "clear": True,
            },
            {
                "action": "http", "label": "Reject ❌",
                "url": f"{base_ntfy_url}/{NTFY_RESPONSE_TOPIC}", "method": "POST",
                "body": json.dumps({"id": confirmation_id, "decision": "reject"}),
                "headers": {"Content-Type": "application/json", "X-Title": f"Rejected tweet {confirmation_id[:8]}"}, "clear": True,
            }
        ]
    }
    try:
        requests.post(base_ntfy_url, json=message_payload, timeout=10)
        print(f"Confirmation request sent to ntfy topic '{base_ntfy_url}/{NTFY_CONFIRM_TOPIC}'. Waiting for response on '{base_ntfy_url}/{NTFY_RESPONSE_TOPIC}' for ID {confirmation_id[:8]}...")
    except requests.exceptions.RequestException as e:
        print(f"Error sending ntfy notification: {e}. Falling back to terminal confirmation.")
        user_input = input(f"Ntfy send failed. Post tweet '{tweet_text[:70].replace('\n', ' ')}...' anyway? (yes/no): ").strip().lower()
        return user_input in ['yes', 'y']

    # Poll for response
    start_time = time.time()
    last_processed_ntfy_event_id = str(int(start_time) - 10) # Look back a few seconds initially

    poll_url = f"{base_ntfy_url}/{NTFY_RESPONSE_TOPIC}/json"
    try:
        resp = requests.get(poll_url, stream=True)
        approved = False
        for line in resp.iter_lines():
            if line:
                event = json.loads(line.decode('utf-8'))
                if event.get("event") == "message":
                    message_payload = json.loads(event.get("message", "{}"))
                    if message_payload.get("id") == confirmation_id:
                        decision = message_payload.get("decision")
                        print(f"Received decision via ntfy: '{decision}' for ID {confirmation_id[:8]}")
                        return decision == "approve"
    except requests.exceptions.ConnectionError as e:
        print(f"Polling ntfy failed due to ConnectionError for URL {poll_url}: {e}. Retrying...")
        time.sleep(5) # Wait before retrying connection issues
    except requests.exceptions.Timeout as e:
        print(f"Polling ntfy timed out for URL {poll_url}: {e}. Retrying...")
        time.sleep(5) # Wait longer before retrying connection issues
    except requests.exceptions.RequestException as e:
        print(f"Error polling ntfy response: {e}. Retrying in 10s.")
        time.sleep(10)

    print(f"No response received via ntfy for ID {confirmation_id[:8]} within {confirmation_timeout_seconds}s. Tweet will not be posted.")
    return False

def main():
    """
    Main function to run the tweet generation process.
    """
    if not all([CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET]):
        raise ValueError("Please set your X API credentials as environment variables.")

    load_llama3_model()

    x_client = tweepy.Client(
        bearer_token=BEARER_TOKEN,  
        consumer_key=CONSUMER_KEY,
        consumer_secret=CONSUMER_SECRET,
        access_token=ACCESS_TOKEN,
        access_token_secret=ACCESS_TOKEN_SECRET
    )

    topics = [
        "kubernetes", "docker", "c++", "golang", "java", "nodejs", "redis",
        "python", "system design", "data structures and algorithms",
        "operating system", "computer networking", "databases", "kafka", "javascript"
    ]

    print(f"Starting scheduled task to run every {TWEET_TIMEGAP_SECS} seconds. Press Ctrl+C to stop.")

    try:
        while True:
            selected_topic = random.choice(topics)
            tweet = generate_technical_tweet(selected_topic)
            print(f"\n--- Proposed Tweet for Twitter ---\n'{tweet}'")

            confirmed_to_post = request_phone_confirmation_ntfy(tweet, TWEET_CONFIRMATION_TIMEOUT_SECS)

            if confirmed_to_post:
                print("Confirmation received. Posting tweet...")
                response = x_client.create_tweet(text=tweet)
                print("Tweet posted successfully!")
                print(f"Tweet ID: {response.data['id']}")
                print(f"Tweet Text: {response.data['text']}")
            else:
                print("Tweet posting cancelled or timed out.")

            print(f"Waiting for {TWEET_TIMEGAP_SECS} seconds before next cycle...")
            time.sleep(TWEET_TIMEGAP_SECS)
    except KeyboardInterrupt:
        print("\nTask stopped by user.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()